import {
	heading,
	heading2,
	mainContent,
	mainContent2,
	subContent,
	subContent2,
} from './utilities/fonts';
import NavLayout from './components/Nav/layout';

export const metadata = {
	title: 'Trinity Anglican Church, Halifax',
	description: 'Generated by create next app',
};

// TODO - Add F

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div
			className={`
            			// Fonts // 
						${heading.variable} 
						${heading2.variable} 
						${mainContent.variable}
						${mainContent2.variable}
						${subContent.variable}
						${subContent2.variable}
						`}>
			<div className='bg-secondary pt-7 h-[100%]'>
				<NavLayout />
				<main className='h-full'>{children}</main>
				{/* <Footer /> */}
			</div>
		</div>
	);
}
