import StaffBanner from './staff/StaffBanner';
import StaffPage from './staff/StaffPage';

type LayoutProps = {
	children: React.ReactNode;
};

export const metadata = {
	title: 'Trinity Anglican Church, Halifax',
	description: 'Generated by create next app',
};

export default function Layout({ children }: LayoutProps) {
	return (
		<>
			<main className='h-full'>{children}</main>

			<StaffBanner />
			<StaffPage />

			<div className='container mx-auto px-4 sm:px-6 md:px-8 lg:px-10 xl:px-12 2xl:px-14'>
				<div className='flex flex-col h-screen'>
					<div className='flex flex-row flex-grow '>
						{/* <StaffList /> */}
						{/* <StaffDetails /> */}
					</div>
				</div>
			</div>
		</>
	);
}
