import './globals.css';
import {
	heading,
	heading2,
	mainContent,
	mainContent2,
	subContent,
	subContent2,
} from './site/utilities/fonts';
import NavBar from './site/components/navbar';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang='en'
			// data-theme='corporate'
			data-theme='business'>
			<body>
				<div
					className={`
            			// Fonts // 
						${heading.variable} 
						${heading2.variable} 
						${mainContent.variable}
						${mainContent2.variable}
						${subContent.variable}
						${subContent2.variable}
						`}>
					<div className='bg-secondary pt-7 h-[100%] HELLO'>
						{/* <div className='hidden lg:block'> */}
						{/* @ts-expect-error Async Server Component */}
						<NavBar props={mainContent} />
						{/* </div> */}
						<main className='h-full'>{children}</main>
						{/* <Footer /> */}
					</div>
				</div>
			</body>
		</html>
	);
}
